export const CALCULATE_NUMBER = 'CALCULATE_SUCCESS';
export const CALCULATE_NUMBER_SUCCESS = 'CALCULATE_SUCCESS';
export const CALCULATE_NUMBER_ERROR = 'CALCULATE_ERROR';
export const CALCULATE_NUMBER_IS_LOADING = 'CALCULATE_IS_LOADING';
